import test from 'node:test';
import assert from 'node:assert/strict';
import {Adventure3D,DIFFICULTIES,TREES,FRIENDS,KEYS,STARS,BONES,STATIC_SOLIDS,solidsFor} from '../adventure3d.js';
import {BODY,penetrates,segmentHit,safeCamera} from '../collision3d.js';
import {rescueRoute,fightBoss} from './3d-playthrough.mjs';
const fresh=(difficulty='normal')=>{const g=new Adventure3D(null,{difficulty});g.start();return g;};
const run=(g,time,input={},hz=60)=>{for(let i=0;i<time*hz;i++)g.tick(1/hz,input);};
const noEnemies=g=>{for(const e of g.enemies)g.defeated.add(e.id);};
const unlock=g=>{for(const k of KEYS)g.collected.add(k.id);for(const f of FRIENDS)g.rescued.add(f.id);g.solids=solidsFor(g.rescued);};

test('trunks stop walking and dashing from every direction at low and high frame rates',()=>{
 const tree=TREES.find(t=>t.x===21&&t.z===5);
 for(const hz of [10,30,60,120])for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]])for(const dash of [false,true]){
  const g=fresh();noEnemies(g);Object.assign(g.player,{x:tree.x-dx*3,z:tree.z-dz*3});
  for(let frame=0;frame<hz;frame++){g.tick(1/hz,{x:dx,z:dz,dash:dash&&frame===0});assert.ok(Math.hypot(g.player.x-tree.x,g.player.z-tree.z)>=tree.scale*.28+BODY.radius-1e-4,`tree penetrated at ${hz}`);}
  assert.ok((g.player.x-tree.x)*dx+(g.player.z-tree.z)*dz<0,'must stay on the approach side');
 }
});
test('lighthouse wall and a roof chimney are solid',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{x:-39,z:-30});run(g,1,{z:-1,dash:true});assert.ok(g.player.z>-32.53);Object.assign(g.player,{x:-24,y:3.4,z:7,vy:0,grounded:true});run(g,1,{x:1,dash:true});assert.ok(g.player.x<-23.05);});
test('closed cages block passage, open only from outside with a key, then release collision',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{x:30,z:-6.5});run(g,1,{z:-1,dash:true});assert.ok(g.player.z>=-7.021);g.interact();assert.equal(g.rescued.size,0);g.collected.add(KEYS[0].id);g.interact();assert.ok(g.rescued.has('spark'));assert.equal(g.keyCount,0);run(g,.5,{z:-1});assert.ok(g.player.z<-9);});
test('bridge rail blocks a sideways dash but can be jumped over',()=>{const g=fresh();unlock(g);noEnemies(g);Object.assign(g.player,{x:0,y:.5,z:-49});run(g,.5,{x:1,dash:true});assert.ok(g.player.x<=2.041);g.tick(1/60,{jump:true});run(g,.3);run(g,.3,{x:1});assert.ok(g.player.x>3,'jump clears the actual railing height');});
test('mushrooms allow walking beneath the cap, but the stem and underside are solid',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{x:34,y:0,z:13.6});run(g,.8,{x:1});assert.ok(g.player.x>39.9);assert.equal(g.player.y,0);Object.assign(g.player,{x:35,y:0,z:12,vy:0});run(g,.5,{x:1});assert.ok(g.player.x<35.93);Object.assign(g.player,{x:35.2,y:0,z:12,vy:0,jumps:0,grounded:true});g.tick(1/60,{jump:true});let max=0;for(let i=0;i<80;i++){g.tick(1/120);max=Math.max(max,g.player.y);}assert.ok(max<=3.2-BODY.height+.001,`head crossed cap: ${max}`);});
test('the sandy beach is solid instead of a hidden fall-through strip',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{x:0,z:47});run(g,.3,{z:1});run(g,.4);assert.equal(g.player.y,-.1);assert.equal(g.player.hp,5);});
test('short ledges step smoothly without jumping or sinking',()=>{const g=fresh();unlock(g);noEnemies(g);Object.assign(g.player,{x:0,z:-40});let lastZ=g.player.z;for(let i=0;i<300;i++){g.tick(1/120,{z:-1});assert.ok(g.player.z<=lastZ+.001);lastZ=g.player.z;}assert.ok(g.player.z<-58);assert.equal(g.player.y,1.2);});
test('bark cannot damage enemies through house walls',()=>{const g=fresh();noEnemies(g);const e=g.enemies[0];g.defeated.delete(e.id);Object.assign(e,{x:-24,y:0,z:11});Object.assign(g.player,{x:-24,y:0,z:13});g.bark();assert.equal(e.hp,2);});
test('enemies cannot chase through the lighthouse or wander into the sea',()=>{const g=fresh();noEnemies(g);const e=g.enemies[0];g.defeated.delete(e.id);Object.assign(e,{x:-39,z:-30,homeX:-39,homeZ:-30});Object.assign(g.player,{x:-39,z:-39});for(let i=0;i<1200;i++){g.tick(1/120);assert.ok(!g.solids.some(s=>s.id.startsWith('lighthouse')&&penetrates(e,s,.55,1.2)));}assert.ok(Math.abs(e.x)<48&&e.z>-45);});
test('items cannot be collected through a solid surface',()=>{const g=fresh();noEnemies(g);const bone=BONES.find(b=>b.y>4&&b.x===-24);Object.assign(g.player,{x:bone.x,y:2.9,z:bone.z,grounded:false,vy:0});g.tick(1/120);assert.ok(!g.collected.has(bone.id));});
test('all items and checkpoints have clear space rather than being buried inside props or cages',()=>{
 const g=fresh();for(const item of [...KEYS,...STARS,...BONES]){const obstructed=g.solids.filter(s=>item.y>s.bottom+.05&&item.y<s.top-.05&&penetrates({x:item.x,y:item.y-.1,z:item.z},s,.1,.2));assert.equal(obstructed.length,0,`${item.id}: ${obstructed.map(s=>s.id)}`);}
});
test('camera remains in front of houses trees cages and the lighthouse',()=>{const g=fresh();for(const id of ['house1','tree-25','lighthouse-base','cage-spark','gate']){const s=g.solids.find(s=>s.id===id),r=s.radius||s.d/2;const target={x:s.x,y:s.bottom+1,z:s.z+r+2},desired={x:s.x,y:s.bottom+1,z:s.z-r-4};const resolved=safeCamera(target,desired,g.solids);assert.ok(resolved.z>desired.z);assert.equal(segmentHit(target,resolved,s),null,id);}});
test('camera never crosses a wall during a close orbit',()=>{const s=STATIC_SOLIDS.find(s=>s.id==='house1');for(let i=0;i<360;i++){const a=i*Math.PI/180,t={x:-24,y:1.3,z:12.02},end={x:t.x+Math.sin(a)*10,y:5,z:t.z+Math.cos(a)*10};const c=safeCamera(t,end,[s]);assert.equal(segmentHit(t,c,s),null,`angle ${i}`);}});
test('coyote time gives a first jump just after walking off a roof',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{x:-24,y:3.4,z:4.6});while(g.player.grounded)g.tick(1/120,{z:-1});assert.ok(g.player.coyote>0);g.tick(1/120,{jump:true});assert.equal(g.player.jumps,1);assert.ok(g.player.vy>10);g.tick(1/120,{jump:true});assert.equal(g.player.jumps,2);});
test('a jump pressed just before landing is buffered until the ground is reached',()=>{const g=fresh();noEnemies(g);Object.assign(g.player,{y:.12,vy:-5,jumps:2,grounded:false,coyote:0});g.tick(1/120,{jump:true});run(g,.1);assert.ok(g.player.y>.2);assert.ok(g.player.vy>0);assert.equal(g.player.jumps,1);});
test('revisiting the same checkpoint heals, while staying on it cannot grant continuous invulnerability',()=>{const g=fresh();g.player.hp=3;run(g,.2);assert.equal(g.player.hp,3);run(g,.5,{z:-1});run(g,.5,{z:1});assert.equal(g.player.hp,5);g.player.hp=2;run(g,.2);assert.equal(g.player.hp,2);});
test('death cannot be bypassed through the menu and retry resets cooldowns',()=>{const g=fresh();g.player.hp=1;g.hurt();assert.equal(g.status,'dead');g.pause();g.player.barkCD=.6;g.player.dashCD=1;g.start();assert.equal(g.status,'playing');assert.equal(g.player.hp,5);assert.equal(g.player.barkCD,0);assert.equal(g.player.dashCD,0);});
test('leaving the arena clears the boss waves and resets the fight',()=>{const g=fresh();unlock(g);Object.assign(g.player,{x:0,y:1.2,z:-64});g.tick(1/60);g.boss.hp=2;g.waves.push({x:0,z:-60,r:3});g.player.z=-54;const hp=g.player.hp;g.tick(1/60);assert.equal(g.boss.state,'sleep');assert.equal(g.boss.hp,8);assert.equal(g.waves.length,0);assert.equal(g.player.hp,hp);});
test('the resting boss remains a solid body instead of allowing the player to stand inside it',()=>{const g=fresh();unlock(g);Object.assign(g.player,{x:0,y:1.2,z:-64});g.boss.state='rest';g.boss.timer=50;g.boss.z=-68;run(g,1,{z:-1});assert.ok(Math.hypot(g.player.x-g.boss.x,g.player.z-g.boss.z)>=2.14);});
test('difficulty is validated, persisted, and safely changeable without losing collectibles',()=>{for(const mode of Object.keys(DIFFICULTIES)){const g=fresh(mode);g.collected.add(BONES[0].id);g.pause();assert.equal(g.setDifficulty(mode),true);const restored=new Adventure3D(g.snapshot());assert.equal(restored.difficulty,mode);assert.equal(restored.maxHP,DIFFICULTIES[mode].hp);assert.equal(restored.boss.hp,DIFFICULTIES[mode].bossHP);assert.equal(restored.boneCount,1);g.resume();assert.equal(g.setDifficulty('easy'),false);}for(const bad of ['constructor','__proto__','nonsense']){const g=new Adventure3D({version:3,difficulty:bad});assert.equal(g.difficulty,'normal');assert.equal(g.setDifficulty(bad),false);}});
test('fall penalties and invulnerability durations match the selected difficulty',()=>{for(const mode of Object.keys(DIFFICULTIES)){const g=fresh(mode);g.player.y=-8;g.tick(1/60);assert.equal(g.player.hp,g.maxHP-g.rules.fallDamage);g.player.invuln=0;g.hurt();assert.equal(g.player.invuln,g.rules.invulnerability);}});
test('changing difficulty cannot resurrect an already defeated boss',()=>{const g=fresh();unlock(g);g.boss.hp=0;g.boss.state='defeated';g.pause();g.setDifficulty('hard');assert.equal(g.boss.hp,0);assert.equal(new Adventure3D(g.snapshot()).boss.hp,0);});
test('old version 3 saves migrate to Normal and preserve rescued friends',()=>{const g=new Adventure3D({version:3,collected:KEYS.map(k=>k.id),rescued:FRIENDS.map(f=>f.id),checkpoint:'boss'});assert.equal(g.difficulty,'normal');assert.equal(g.rescued.size,3);assert.ok(!g.solids.some(s=>s.id==='gate'));assert.equal(g.player.z,-58);});
test('invalid dt and input values cannot corrupt player coordinates',()=>{const g=fresh();g.tick(NaN,{x:Infinity});g.tick(-1);g.tick(1/60,{x:Infinity,z:NaN,yaw:Infinity});for(const axis of ['x','y','z'])assert.ok(Number.isFinite(g.player[axis]));});

for(const mode of ['easy','normal','hard'])for(const hz of [15,30,60,120])test(`complete rescue and boss victory using player inputs: ${mode} at ${hz} Hz`,()=>{const g=fresh(mode);rescueRoute(g,hz);fightBoss(g,hz);assert.equal(g.rescued.size,3);assert.ok(g.player.hp>0);const restored=new Adventure3D(g.snapshot());assert.equal(restored.boss.hp,0);assert.equal(restored.rescued.size,3);assert.equal(restored.difficulty,mode);});
